service: cloakman
image: w3const/cloakman
require_destination: true

registry:
  username: w3const

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    SOLID_QUEUE_IN_PUMA: true
    TZ: Asia/Tokyo

  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64

  args:
    APP_GID: 11370
    APP_UID: 2233

ssh:
  user: w3const

accessories:
  keycloak:
    image: keycloak/keycloak:26.2.3
    cmd: start --http-enabled true --hostname-strict false --proxy-headers xforwarded

    proxy:
      app_port: 8080

      healthcheck:
        path: /

    env:
      secret:
        - KC_DB_PASSWORD
        - KC_DB_USERNAME
        - KEYCLOAK_ADMIN
        - KEYCLOAK_ADMIN_PASSWORD

      clear:
        KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
        TZ: Asia/Tokyo

    files:
      - keycloak/conf/truststores/mail1i.crt:/opt/keycloak/conf/truststores/mail1i.crt
      - keycloak/providers/keycloak-magic-link-0.36.jar:/opt/keycloak/providers/keycloak-magic-link-0.36.jar
      - keycloak/themes/ddbj/login/login-reset-password.ftl:/opt/keycloak/themes/ddbj/login/login-reset-password.ftl
      - keycloak/themes/ddbj/login/login-update-password.ftl:/opt/keycloak/themes/ddbj/login/login-update-password.ftl
      - keycloak/themes/ddbj/login/login.ftl:/opt/keycloak/themes/ddbj/login/login.ftl
      - keycloak/themes/ddbj/login/otp-form.ftl:/opt/keycloak/themes/ddbj/login/otp-form.ftl
      - keycloak/themes/ddbj/login/password-commons.ftl:/opt/keycloak/themes/ddbj/login/password-commons.ftl
      - keycloak/themes/ddbj/login/resources/img/logo.png:/opt/keycloak/themes/ddbj/login/resources/img/logo.png
      - keycloak/themes/ddbj/login/template.ftl:/opt/keycloak/themes/ddbj/login/template.ftl
      - keycloak/themes/ddbj/login/theme.properties:/opt/keycloak/themes/ddbj/login/theme.properties

  keycloak-postgres:
    image: postgres:17.5

    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER

      clear:
        POSTGRES_DB: keycloak

  openldap:
    image: bitnami/openldap:2.6.9
    port: 636:1636

    env:
      secret:
        - LDAP_ADMIN_PASSWORD
        - LDAP_ADMIN_USERNAME
        - LDAP_CONFIG_ADMIN_PASSWORD
        - LDAP_CONFIG_ADMIN_USERNAME

      clear:
        LDAP_ALLOW_ANON_BINDING: 'no'
        LDAP_CONFIG_ADMIN_ENABLED: 'yes'
        LDAP_ENABLE_TLS: 'yes'
        LDAP_ROOT: dc=ddbj,dc=nig,dc=ac,dc=jp
        LDAP_SKIP_DEFAULT_TREE: 'yes'
        LDAP_TLS_CA_FILE: /certs/ca.crt
        LDAP_TLS_CERT_FILE: /certs/server.crt
        LDAP_TLS_KEY_FILE: /certs/server.key
        TZ: Asia/Tokyo

    files:
      - openldap/docker-entrypoint-initdb.d/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - openldap/docker-entrypoint-initdb.d/ldifs/acl.ldif:/docker-entrypoint-initdb.d/ldifs/acl.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/index.ldif:/docker-entrypoint-initdb.d/ldifs/index.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/lastbind.ldif:/docker-entrypoint-initdb.d/ldifs/lastbind.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/unique.ldif:/docker-entrypoint-initdb.d/ldifs/unique.ldif
      - openldap/ldifs/init.ldif:/ldifs/init.ldif
      - openldap/schemas/ddbj.ldif:/schemas/ddbj.ldif
      - openldap/schemas/inetuser.ldif:/schemas/inetuser.ldif
      - openldap/schemas/openssh-lpk.ldif:/schemas/openssh-lpk.ldif

  redis:
    image: redis:7.4.2
    cmd: redis-server --appendonly yes

    env:
      clear:
        TZ: Asia/Tokyo
