service: cloakman
image: ursm/cloakman
require_destination: true

registry:
  username: ursm

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - KEYCLOAK_CLIENT_SECRET
    - RAILS_MASTER_KEY

  clear:
    KEYCLOAK_CLIENT_ID: cloakman
    KEYCLOAK_REALM: master
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "cloakman_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

deploy_timeout: 120

accessories:
  keycloak:
    image: keycloak/keycloak:25.0
    cmd: start-dev

    proxy:
      app_port: 8080

      healthcheck:
        path: /

    env:
      secret:
        - KEYCLOAK_ADMIN
        - KEYCLOAK_ADMIN_PASSWORD

      clear:
        KC_HTTP_ENABLED: true
        KC_PROXY: edge

    volumes:
      - cloakman_keycloak:/opt/keycloak/data

  openldap:
    image: bitnami/openldap:2.6

    env:
      secret:
        - LDAP_ADMIN_USERNAME
        - LDAP_ADMIN_PASSWORD

      clear:
        LDAP_ROOT: dc=ddbj,dc=nig,dc=ac,dc=jp
        LDAP_SKIP_DEFAULT_TREE: 'yes'

    files:
      - openldap/ldifs/init.ldif:/ldifs/init.ldif
      - openldap/schemas/ddbj.ldif:/schemas/ddbj.ldif
      - openldap/schemas/openssh-lpk.ldif:/schemas/openssh-lpk.ldif

    volumes:
      - cloakman_openldap:/bitnami/openldap
