service: cloakman
image: w3const/cloakman
require_destination: true

registry:
  username: w3const

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - EXT_LDAP_BIND_DN
    - EXT_LDAP_PASSWORD
    - KEYCLOAK_CLIENT_ID
    - KEYCLOAK_CLIENT_SECRET
    - LDAP_ADMIN_BIND_DN
    - LDAP_ADMIN_PASSWORD
    - SECRET_KEY_BASE
    - SENTRY_DSN

  clear:
    EXT_LDAP_BASE_DN: dc=nig,dc=ac,dc=jp
    EXT_LDAP_HOST: 172.19.25.251
    EXT_LDAP_PORT: 636
    KEYCLOAK_REALM: master
    LDAP_BASE_DN: dc=ddbj,dc=nig,dc=ac,dc=jp
    LDAP_HOST: cloakman-openldap
    LDAP_PORT: 1389
    REDIS_URL: redis://cloakman-redis:6379
    SOLID_QUEUE_IN_PUMA: true
    TZ: Asia/Tokyo

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64

  args:
    APP_GID: 11370
    APP_UID: 2233

ssh:
  user: w3const

accessories:
  keycloak:
    image: keycloak/keycloak:26.1
    cmd: start --http-enabled true --hostname-strict false --proxy-headers xforwarded

    proxy:
      app_port: 8080

      healthcheck:
        path: /

    env:
      secret:
        - KEYCLOAK_ADMIN
        - KEYCLOAK_ADMIN_PASSWORD

      clear:
        TZ: Asia/Tokyo

    files:
      - keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar
      - keycloak/themes/ddbj/login/cli_splash.ftl:/opt/keycloak/themes/ddbj/login/cli_splash.ftl
      - keycloak/themes/ddbj/login/code.ftl:/opt/keycloak/themes/ddbj/login/code.ftl
      - keycloak/themes/ddbj/login/delete-account-confirm.ftl:/opt/keycloak/themes/ddbj/login/delete-account-confirm.ftl
      - keycloak/themes/ddbj/login/delete-credential.ftl:/opt/keycloak/themes/ddbj/login/delete-credential.ftl
      - keycloak/themes/ddbj/login/error.ftl:/opt/keycloak/themes/ddbj/login/error.ftl
      - keycloak/themes/ddbj/login/footer.ftl:/opt/keycloak/themes/ddbj/login/footer.ftl
      - keycloak/themes/ddbj/login/frontchannel-logout.ftl:/opt/keycloak/themes/ddbj/login/frontchannel-logout.ftl
      - keycloak/themes/ddbj/login/idp-review-user-profile.ftl:/opt/keycloak/themes/ddbj/login/idp-review-user-profile.ftl
      - keycloak/themes/ddbj/login/info.ftl:/opt/keycloak/themes/ddbj/login/info.ftl
      - keycloak/themes/ddbj/login/login-config-totp.ftl:/opt/keycloak/themes/ddbj/login/login-config-totp.ftl
      - keycloak/themes/ddbj/login/login-idp-link-confirm-override.ftl:/opt/keycloak/themes/ddbj/login/login-idp-link-confirm-override.ftl
      - keycloak/themes/ddbj/login/login-idp-link-confirm.ftl:/opt/keycloak/themes/ddbj/login/login-idp-link-confirm.ftl
      - keycloak/themes/ddbj/login/login-idp-link-email.ftl:/opt/keycloak/themes/ddbj/login/login-idp-link-email.ftl
      - keycloak/themes/ddbj/login/login-oauth-grant.ftl:/opt/keycloak/themes/ddbj/login/login-oauth-grant.ftl
      - keycloak/themes/ddbj/login/login-oauth2-device-verify-user-code.ftl:/opt/keycloak/themes/ddbj/login/login-oauth2-device-verify-user-code.ftl
      - keycloak/themes/ddbj/login/login-otp.ftl:/opt/keycloak/themes/ddbj/login/login-otp.ftl
      - keycloak/themes/ddbj/login/login-page-expired.ftl:/opt/keycloak/themes/ddbj/login/login-page-expired.ftl
      - keycloak/themes/ddbj/login/login-passkeys-conditional-authenticate.ftl:/opt/keycloak/themes/ddbj/login/login-passkeys-conditional-authenticate.ftl
      - keycloak/themes/ddbj/login/login-password.ftl:/opt/keycloak/themes/ddbj/login/login-password.ftl
      - keycloak/themes/ddbj/login/login-recovery-authn-code-config.ftl:/opt/keycloak/themes/ddbj/login/login-recovery-authn-code-config.ftl
      - keycloak/themes/ddbj/login/login-recovery-authn-code-input.ftl:/opt/keycloak/themes/ddbj/login/login-recovery-authn-code-input.ftl
      - keycloak/themes/ddbj/login/login-reset-otp.ftl:/opt/keycloak/themes/ddbj/login/login-reset-otp.ftl
      - keycloak/themes/ddbj/login/login-update-password.ftl:/opt/keycloak/themes/ddbj/login/login-update-password.ftl
      - keycloak/themes/ddbj/login/login-update-profile.ftl:/opt/keycloak/themes/ddbj/login/login-update-profile.ftl
      - keycloak/themes/ddbj/login/login-username.ftl:/opt/keycloak/themes/ddbj/login/login-username.ftl
      - keycloak/themes/ddbj/login/login-verify-email.ftl:/opt/keycloak/themes/ddbj/login/login-verify-email.ftl
      - keycloak/themes/ddbj/login/login-x509-info.ftl:/opt/keycloak/themes/ddbj/login/login-x509-info.ftl
      - keycloak/themes/ddbj/login/logout-confirm.ftl:/opt/keycloak/themes/ddbj/login/logout-confirm.ftl
      - keycloak/themes/ddbj/login/messages/messages_en.properties:/opt/keycloak/themes/ddbj/login/messages/messages_en.properties
      - keycloak/themes/ddbj/login/password-commons.ftl:/opt/keycloak/themes/ddbj/login/password-commons.ftl
      - keycloak/themes/ddbj/login/register-commons.ftl:/opt/keycloak/themes/ddbj/login/register-commons.ftl
      - keycloak/themes/ddbj/login/register.ftl:/opt/keycloak/themes/ddbj/login/register.ftl
      - keycloak/themes/ddbj/login/resources/js/authChecker.js:/opt/keycloak/themes/ddbj/login/resources/js/authChecker.js
      - keycloak/themes/ddbj/login/resources/js/common.js:/opt/keycloak/themes/ddbj/login/resources/js/common.js
      - keycloak/themes/ddbj/login/resources/js/kcMultivalued.js:/opt/keycloak/themes/ddbj/login/resources/js/kcMultivalued.js
      - keycloak/themes/ddbj/login/resources/js/kcNumberFormat.js:/opt/keycloak/themes/ddbj/login/resources/js/kcNumberFormat.js
      - keycloak/themes/ddbj/login/resources/js/kcNumberUnFormat.js:/opt/keycloak/themes/ddbj/login/resources/js/kcNumberUnFormat.js
      - keycloak/themes/ddbj/login/resources/js/menu-button-links.js:/opt/keycloak/themes/ddbj/login/resources/js/menu-button-links.js
      - keycloak/themes/ddbj/login/resources/js/passkeysConditionalAuth.js:/opt/keycloak/themes/ddbj/login/resources/js/passkeysConditionalAuth.js
      - keycloak/themes/ddbj/login/resources/js/passwordVisibility.js:/opt/keycloak/themes/ddbj/login/resources/js/passwordVisibility.js
      - keycloak/themes/ddbj/login/resources/js/userProfile.js:/opt/keycloak/themes/ddbj/login/resources/js/userProfile.js
      - keycloak/themes/ddbj/login/resources/js/webauthnAuthenticate.js:/opt/keycloak/themes/ddbj/login/resources/js/webauthnAuthenticate.js
      - keycloak/themes/ddbj/login/resources/js/webauthnRegister.js:/opt/keycloak/themes/ddbj/login/resources/js/webauthnRegister.js
      - keycloak/themes/ddbj/login/resources/img/logo.png:/opt/keycloak/themes/ddbj/login/resources/img/logo.png
      - keycloak/themes/ddbj/login/saml-post-form.ftl:/opt/keycloak/themes/ddbj/login/saml-post-form.ftl
      - keycloak/themes/ddbj/login/select-authenticator.ftl:/opt/keycloak/themes/ddbj/login/select-authenticator.ftl
      - keycloak/themes/ddbj/login/select-organization.ftl:/opt/keycloak/themes/ddbj/login/select-organization.ftl
      - keycloak/themes/ddbj/login/terms.ftl:/opt/keycloak/themes/ddbj/login/terms.ftl
      - keycloak/themes/ddbj/login/update-email.ftl:/opt/keycloak/themes/ddbj/login/update-email.ftl
      - keycloak/themes/ddbj/login/user-profile-commons.ftl:/opt/keycloak/themes/ddbj/login/user-profile-commons.ftl
      - keycloak/themes/ddbj/login/webauthn-authenticate.ftl:/opt/keycloak/themes/ddbj/login/webauthn-authenticate.ftl
      - keycloak/themes/ddbj/login/webauthn-error.ftl:/opt/keycloak/themes/ddbj/login/webauthn-error.ftl
      - keycloak/themes/ddbj/login/webauthn-register.ftl:/opt/keycloak/themes/ddbj/login/webauthn-register.ftl
      - keycloak/themes/ddbj/login/login.ftl:/opt/keycloak/themes/ddbj/login/login.ftl
      - keycloak/themes/ddbj/login/login-reset-password.ftl:/opt/keycloak/themes/ddbj/login/login-reset-password.ftl
      - keycloak/themes/ddbj/login/template.ftl:/opt/keycloak/themes/ddbj/login/template.ftl

  openldap:
    image: bitnami/openldap:2.6
    port: 636:1636

    env:
      secret:
        - LDAP_ADMIN_PASSWORD
        - LDAP_ADMIN_USERNAME
        - LDAP_CONFIG_ADMIN_PASSWORD
        - LDAP_CONFIG_ADMIN_USERNAME

      clear:
        LDAP_ALLOW_ANON_BINDING: 'no'
        LDAP_CONFIGURE_PPOLICY: 'yes'
        LDAP_CONFIG_ADMIN_ENABLED: 'yes'
        LDAP_ENABLE_TLS: 'yes'
        LDAP_ROOT: dc=ddbj,dc=nig,dc=ac,dc=jp
        LDAP_SKIP_DEFAULT_TREE: 'yes'
        LDAP_TLS_CA_FILE: /certs/ca.crt
        LDAP_TLS_CERT_FILE: /certs/server.crt
        LDAP_TLS_KEY_FILE: /certs/server.key
        TZ: Asia/Tokyo

    files:
      - openldap/docker-entrypoint-initdb.d/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - openldap/docker-entrypoint-initdb.d/ldifs/acl.ldif:/docker-entrypoint-initdb.d/ldifs/acl.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/index.ldif:/docker-entrypoint-initdb.d/ldifs/index.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/lastbind.ldif:/docker-entrypoint-initdb.d/ldifs/lastbind.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/unique.ldif:/docker-entrypoint-initdb.d/ldifs/unique.ldif
      - openldap/ldifs/init.ldif:/ldifs/init.ldif
      - openldap/schemas/ddbj.ldif:/schemas/ddbj.ldif
      - openldap/schemas/inetuser.ldif:/schemas/inetuser.ldif
      - openldap/schemas/openssh-lpk.ldif:/schemas/openssh-lpk.ldif

  redis:
    image: redis:7.4
    cmd: redis-server --appendonly yes

    env:
      clear:
        TZ: Asia/Tokyo
