servers:
  web:
    - bastion

proxy:
  ssl: false
  host: cloakman.ursm.jp

env:
  clear:
    APP_URL: https://cloakman.ursm.jp
    KEYCLOAK_URL: https://keycloak.ursm.jp
    LDAP_INTERNAL_ENDPOINT: ldaps://172.19.7.244:636
    SENTRY_CURRENT_ENV: staging

accessories:
  keycloak:
    host: bastion

    proxy:
      host: keycloak.ursm.jp

  openldap:
    host: bastion
