service: cloakman
image: ursm/cloakman
require_destination: true

registry:
  username: ursm

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - KEYCLOAK_CLIENT_SECRET
    - RAILS_MASTER_KEY

  clear:
    KEYCLOAK_CLIENT_ID: cloakman
    KEYCLOAK_REALM: master
    REDIS_URL: redis://redis:6379
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "cloakman_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ursm

deploy_timeout: 120

accessories:
  keycloak:
    image: keycloak/keycloak:26.0
    cmd: start --http-enabled true --hostname-strict false --proxy-headers xforwarded

    proxy:
      app_port: 8080

      healthcheck:
        path: /

    env:
      secret:
        - KEYCLOAK_ADMIN
        - KEYCLOAK_ADMIN_PASSWORD

    volumes:
      - cloakman_keycloak:/opt/keycloak/data

    files:
      - keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar

  openldap:
    image: bitnami/openldap:2.6

    env:
      secret:
        - LDAP_ADMIN_USERNAME
        - LDAP_ADMIN_PASSWORD

      clear:
        LDAP_ROOT: dc=ddbj,dc=nig,dc=ac,dc=jp
        LDAP_SKIP_DEFAULT_TREE: 'yes'

    volumes:
      - cloakman_openldap:/bitnami/openldap

    files:
      - openldap/ldifs/init.ldif:/ldifs/init.ldif
      - openldap/schemas/ddbj.ldif:/schemas/ddbj.ldif
      - openldap/schemas/openssh-lpk.ldif:/schemas/openssh-lpk.ldif

  redis:
    image: redis:7.4

    volumes:
      - cloakman_redis:/data
