service: cloakman
image: w3const/cloakman
require_destination: true

registry:
  username: w3const

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - EXT_LDAP_BIND_DN
    - EXT_LDAP_PASSWORD
    - KEYCLOAK_CLIENT_ID
    - KEYCLOAK_CLIENT_SECRET
    - LDAP_ADMIN_BIND_DN
    - LDAP_ADMIN_PASSWORD
    - SECRET_KEY_BASE
    - SENTRY_DSN

  clear:
    EXT_LDAP_BASE_DN: dc=nig,dc=ac,dc=jp
    EXT_LDAP_HOST: 172.19.25.251
    EXT_LDAP_PORT: 636
    KEYCLOAK_REALM: master
    LDAP_HOST: cloakman-openldap
    LDAP_PORT: 1389
    REDIS_URL: redis://cloakman-redis:6379
    SOLID_QUEUE_IN_PUMA: true
    TZ: Asia/Tokyo

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64

  args:
    APP_GID: 11370
    APP_UID: 2233

ssh:
  user: w3const

accessories:
  keycloak:
    image: keycloak/keycloak:26.1
    cmd: start --http-enabled true --hostname-strict false --proxy-headers xforwarded

    proxy:
      app_port: 8080

      healthcheck:
        path: /

    env:
      secret:
        - KEYCLOAK_ADMIN
        - KEYCLOAK_ADMIN_PASSWORD

      clear:
        TZ: Asia/Tokyo

    files:
      - keycloak/conf/truststores/mail1i.crt:/opt/keycloak/conf/truststores/mail1i.crt
      - keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar
      - keycloak/themes/ddbj/login/login-reset-password.ftl:/opt/keycloak/themes/ddbj/login/login-reset-password.ftl
      - keycloak/themes/ddbj/login/login-update-password.ftl:/opt/keycloak/themes/ddbj/login/login-update-password.ftl
      - keycloak/themes/ddbj/login/login.ftl:/opt/keycloak/themes/ddbj/login/login.ftl
      - keycloak/themes/ddbj/login/password-commons.ftl:/opt/keycloak/themes/ddbj/login/password-commons.ftl
      - keycloak/themes/ddbj/login/resources/img/logo.png:/opt/keycloak/themes/ddbj/login/resources/img/logo.png
      - keycloak/themes/ddbj/login/template.ftl:/opt/keycloak/themes/ddbj/login/template.ftl
      - keycloak/themes/ddbj/login/theme.properties:/opt/keycloak/themes/ddbj/login/theme.properties

  openldap:
    image: bitnami/openldap:2.6
    port: 636:1636

    env:
      secret:
        - LDAP_ADMIN_PASSWORD
        - LDAP_ADMIN_USERNAME
        - LDAP_CONFIG_ADMIN_PASSWORD
        - LDAP_CONFIG_ADMIN_USERNAME

      clear:
        LDAP_ALLOW_ANON_BINDING: 'no'
        LDAP_CONFIGURE_PPOLICY: 'yes'
        LDAP_CONFIG_ADMIN_ENABLED: 'yes'
        LDAP_ENABLE_TLS: 'yes'
        LDAP_ROOT: dc=ddbj,dc=nig,dc=ac,dc=jp
        LDAP_SKIP_DEFAULT_TREE: 'yes'
        LDAP_TLS_CA_FILE: /certs/ca.crt
        LDAP_TLS_CERT_FILE: /certs/server.crt
        LDAP_TLS_KEY_FILE: /certs/server.key
        TZ: Asia/Tokyo

    files:
      - openldap/docker-entrypoint-initdb.d/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - openldap/docker-entrypoint-initdb.d/ldifs/acl.ldif:/docker-entrypoint-initdb.d/ldifs/acl.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/index.ldif:/docker-entrypoint-initdb.d/ldifs/index.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/lastbind.ldif:/docker-entrypoint-initdb.d/ldifs/lastbind.ldif
      - openldap/docker-entrypoint-initdb.d/ldifs/unique.ldif:/docker-entrypoint-initdb.d/ldifs/unique.ldif
      - openldap/ldifs/init.ldif:/ldifs/init.ldif
      - openldap/schemas/ddbj.ldif:/schemas/ddbj.ldif
      - openldap/schemas/inetuser.ldif:/schemas/inetuser.ldif
      - openldap/schemas/openssh-lpk.ldif:/schemas/openssh-lpk.ldif

  redis:
    image: redis:7.4
    cmd: redis-server --appendonly yes

    env:
      clear:
        TZ: Asia/Tokyo
