servers:
  web:
    - cloakman-staging

proxy:
  host: accounts-staging.ddbj.nig.ac.jp

env:
  clear:
    RAILS_ENV: staging

volumes:
  - ./volumes/cloakman-staging/storage:/rails/storage

accessories:
  keycloak:
    host: cloakman-staging

    proxy:
      host: idp-staging.ddbj.nig.ac.jp

    volumes:
      - ./volumes/cloakman-staging/keycloak:/opt/keycloak/data

  openldap:
    host: cloakman-staging

    volumes:
      - ./volumes/cloakman-staging/openldap:/bitnami/openldap
      - ./volumes/cloakman-staging/openldap-certs:/certs

  redis:
    host: cloakman-staging

    volumes:
      - ./volumes/cloakman-staging/redis:/data
