service: cloakman
image: ursm/cloakman

servers:
  web:
    - bastion

proxy:
  ssl: false
  host: cloakman.ursm.jp

registry:
  username: ursm

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - KEYCLOAK_CLIENT_SECRET
    - RAILS_MASTER_KEY

  clear:
    APP_URL: https://cloakman.ursm.jp
    KEYCLOAK_CLIENT_ID: cloakman
    KEYCLOAK_REALM: master
    KEYCLOAK_URL: https://keycloak.ursm.jp
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "cloakman_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ursm

deploy_timeout: 120

accessories:
  keycloak:
    image: keycloak/keycloak:25.0
    cmd: start-dev
    host: bastion

    proxy:
      host: keycloak.ursm.jp
      app_port: 8080

      healthcheck:
        path: /

    env:
      secret:
        - KEYCLOAK_ADMIN
        - KEYCLOAK_ADMIN_PASSWORD

      clear:
        KC_HTTP_ENABLED: true
        KC_PROXY: edge

    volumes:
      - cloakman_keycloak:/opt/keycloak/data
